import type { Metadata } from "next";
import "./globals.css";
import {DM_Sans} from "next/font/google"

const dm_sans = DM_Sans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "abcxyz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={dm_sans.className}
      >
        {children}
      </body>
    </html>
  );
}
